services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: demoCRM
      POSTGRES_PASSWORD: demoCRM_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookstore.com
      PGADMIN_DEFAULT_PASSWORD: bookstoreadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    
  app:
    build: .
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demoCRM
      SPRING_DATASOURCE_USERNAME: demoCRM
      SPRING_DATASOURCE_PASSWORD: demoCRM_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data: